2023-12-29 20:21:02,971 INFO    StreamThr :103906 [internal.py:wandb_internal():86] W&B internal server running at pid: 103906, started at: 2023-12-29 20:21:02.970746
2023-12-29 20:21:02,972 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: status
2023-12-29 20:21:02,973 INFO    WriterThread:103906 [datastore.py:open_for_write():85] open: /cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/LLaMA-Factory/wandb/run-20231229_202102-3oommjvv/run-3oommjvv.wandb
2023-12-29 20:21:02,974 DEBUG   SenderThread:103906 [sender.py:send():382] send: header
2023-12-29 20:21:02,979 DEBUG   SenderThread:103906 [sender.py:send():382] send: run
2023-12-29 20:21:07,980 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:12,981 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:17,981 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:22,982 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:27,983 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:32,984 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:37,985 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:42,986 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:47,987 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:52,988 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:21:57,989 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:02,990 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:06,624 INFO    SenderThread:103906 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb13e72c2e0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb13e72c2e0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/miniconda3/envs/torch2/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb13e72c2e0>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2023-12-29 20:22:07,991 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:12,992 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:17,993 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:22,993 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:27,994 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: keepalive
2023-12-29 20:22:32,995 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: cancel
2023-12-29 20:22:32,995 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: cancel
2023-12-29 20:22:35,005 DEBUG   HandlerThread:103906 [handler.py:handle_request():146] handle_request: shutdown
2023-12-29 20:22:35,005 INFO    HandlerThread:103906 [handler.py:finish():866] shutting down handler
2023-12-29 20:22:35,996 INFO    WriterThread:103906 [datastore.py:close():294] close: /cpfs01/projects-HDD/cfff-23ba4487e9df_HDD/wangzili/LLaMA-Factory/wandb/run-20231229_202102-3oommjvv/run-3oommjvv.wandb
